FROM node:22-alpine AS base
WORKDIR /app
COPY package*.json ./

RUN npm ci

COPY . .

# ===================================
# Prod (build + nginx)
# ===================================
FROM base AS build-prod
# RUN npm run build --configuration production
RUN npm run build -- --configuration production --project=RunGameFront

FROM nginx:alpine AS prod
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build-prod /app/dist/run-game-front/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
