FROM maven:3.9.8-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml mvnw ./

RUN chmod +x mvnw

COPY .mvn .mvn
RUN ./mvnw dependency:go-offline
COPY src ./src

RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/RunGame.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
